var web='<a href="https://www.nostr.net/">Nostr.net </a>';
web=web+'<a href="https://nostr.io/">.io </a>';
web=web+'<a href="https://nostr.info/relays/">.info </a>';
web=web+'<a href="https://www.nostr.guru/">.guru </a>';
web=web+'<a href="https://nostr-resources.com/">Res </a>&nbsp;';
web=web+'<a href="https://8nostr.com/relays/?Events=100&ms=3000"><b>Relays </b></a>';
web=web+'<a href="https://iris.to/npub16dq3qps8sgehezrylamryx5zrukmhnashvecvjcucjr3927cf2qqd8evcw">☯️iris.to &nbsp;</a>';
web=web+'<a href="https://www.broadcstr.com/npub16dq3qps8sgehezrylamryx5zrukmhnashvecvjcucjr3927cf2qqd8evcw">Broadcstr&nbsp;</a>';
web=web+'<span id="urls">';
web=web+'<a href="https://astral.ninja/npub16dq3qps8sgehezrylamryx5zrukmhnashvecvjcucjr3927cf2qqd8evcw">Astral&nbsp;</a>';
web=web+'<a href="https://yosup.app/profile/d34110060782337c8864ff76321a821f2dbbcfb0bb33864b1cc48712abd84a80">Yosup&nbsp;</a>';
web=web+'<a href="https://web.nostrid.app/account/d34110060782337c8864ff76321a821f2dbbcfb0bb33864b1cc48712abd84a80">Nostrid&nbsp;</a>';
web=web+'<a href="https://hamstr.to/profile/npub16dq3qps8sgehezrylamryx5zrukmhnashvecvjcucjr3927cf2qqd8evcw">Hamstr&nbsp;</a>';
web=web+'<a href="https://snort.social/p/npub16dq3qps8sgehezrylamryx5zrukmhnashvecvjcucjr3927cf2qqd8evcw">Snort&nbsp;</a>';
web=web+'<a href="https://nostr.band/npub16dq3qps8sgehezrylamryx5zrukmhnashvecvjcucjr3927cf2qqd8evcw">Nostr.band&nbsp;</a>';
web=web+'</span>';
document.getElementById("NostrWeb").innerHTML=web;
web='<a href="https://github.com/irislib/iris-messenger/releases">🖥️Desktop&nbsp;</a>';
web=web+'<a href="https://testflight.apple.com/join/5xdoDCmG">🍏：Iris</a>';
web=web+'<a href="https://apps.apple.com/ca/app/damus/id1628663131">&nbsp;Damus&nbsp;</a>';
web=web+'<a href="https://testflight.apple.com/join/WVoBPXE6">ts Plebstr</a>';
web=web+'<a href="https://plebstr.com/#download">&nbsp; </a>';
web=web+'<a href="https://github.com/vitorpamplona/amethyst/releases/">📱：Amethyst</a>&nbsp;';
web=web+'<a href="https://github.com/KoalaSat/nostros/releases">Nostros</a>&nbsp;';
web=web+'<a href="https://pan.baidu.com/s/1V-TA-o4230Ypt8xqgxjqOw?pwd=doge">[云<b>Yun</b>]</a>&nbsp;&nbsp;';
web=web+'<a href="https://nostr.watch/relays/find#public">☯️Map</a>&nbsp;';
web=web+'<B><a href="https://chatforai.com">Chat</a>';
web=web+'<a href="https://94gpt.com">&nbsp;94&nbsp</a>';
web=web+'<a href="https://chatgpt.azurewebsites.net">web&nbsp</a>';
web=web+'<a href="https://fastgpt.app">GPT</a>&nbsp;';
web=web+'<a href="https://ai117.com">&nbsp;AI</a></B>';
document.getElementById("NostrApp").innerHTML=web;
web='<a href="https://lightningaddress.com/">LN@</a>&nbsp;';
web=web+'<a href="https://www.lapps.co/">Lapps</a>&nbsp;';
web=web+'<a href="https://www.bitrefill.com/blog/top-11-lightning-network-wallets-bitrefill/">11</a>&nbsp;';
web=web+'<a href="https://getalby.com/">getAlby</a>';
web=web+'<a href="https://github.com/getAlby/lightning-browser-extension/releases">(Ext)</a>';
web=web+'<a href="https://pan.baidu.com/s/1V-TA-o4230Ypt8xqgxjqOw?pwd=doge"><b>[YUN]</b></a>&nbsp;';
web=web+'<a href="https://github.com/ACINQ/phoenix/releases">Phoenix</a>&nbsp;';
web=web+'<a href="https://github.com/breez/breezmobile/releases">Breez</a>&nbsp;';
web=web+'<a href="https://github.com/muun/apollo">Muun</a>&nbsp;';
web=web+'<a href="https://github.com/ZeusLN/zeus/releases">Zeus</a>&nbsp;';
web=web+'<a href="https://github.com/BlueWallet/BlueWallet/releases">BlueWallet</a>';
web=web+'<a href="https://www.bitrefill.com/thor-lightning-network-channels/?utm_source=medium&utm_medium=blog&utm_campaign=lightning-wallets">&nbsp;BLW</a>';
web=web+'<a href="https://walletofsatoshi.com/">&nbsp;WoS</a>';
document.getElementById("LNlink").innerHTML=web;
web='<a href="https://ahr999.com">9️⃣ahr999.com</a>&nbsp;';
web=web+'<a href="https://wiccm.com/btcdv.com">W/BtcDV.com</a>&nbsp;';
web=web+'<a href="https://btayx.com/btcie.com">📈BtcIE</a>&nbsp;';
web=web+'<a href="https://bitcoinall.org/">BitcoinALL.org</a>&nbsp;';
web=web+'<a href="https://www.bit.pics/">🎨Bit.Pics</a>&nbsp;';
web=web+'<a href="https://idgui.com/n/">idgui.com/n</a>&nbsp;';
web=web+'<a href="https://dogefei.com/">👁️‍🗨️DogeFei</a>&nbsp;';
web=web+'<a href="https://bijingpai.com/">🛒BiJingPai.com</a>&nbsp;';
web=web+'<a href="lightning:cndx@8nostr.com" target=_self>LN</a><a href="https://getalby.com/p/cndx">⚡ &nbsp;</a>';
document.getElementById("Morelink").innerHTML=web;
web='<a target="_self" href="https://ahr999.com" onclick="nip5add(\'ahr999.com\');return false;">@ahr999.com</a> ';
web=web+'<a target="_self" href="https://vbtcv.com" onclick="nip5add(\'vbtcv.com\');return false;">@v₿v.com</a> ';
web=web+'<a target="_self" href="https://btclv.com" onclick="nip5add(\'btclv.com\');return false;">@₿lv.com</a> ';
web=web+'<a target="_self" href="https://btc.pics" onclick="nip5add(\'btc.pics\');return false;">@btc.pics</a> ';
web=web+'<a target="_self" href="https://bitcoinall.org" onclick="nip5add(\'bitcoinall.org\');return false;">@₿all</a>';
document.getElementById("nip5adds").innerHTML=web;
