var web='<a href="https://badges.page/p/d34110060782337c8864ff76321a821f2dbbcfb0bb33864b1cc48712abd84a80">₿adges </a>';
web=web+'<a href="https://btc.pics/img/">₿🖼️<b>IMG</b>&nbsp;</a>';
web=web+'<a href="https://www.nostr.net/">.net</a>';
web=web+'<a href="https://nostr.io/"> </a>';
web=web+'<a href="https://www.nostr.guru/"><b>guru</b> </a>';
web=web+'<a href="https://nostr-resources.com/">res</a>';
web=web+'<a href="https://void.cat/">🗺️VoidCat&nbsp;</a>';
web=web+'<a href="https://postimages.org/">Post&nbsp;</a>';
web=web+'<a href="https://imgse.com/">imgse&nbsp;</a>';
web=web+'<a href="https://www.hd-r.cn/">hd-r&nbsp;</a>';
web=web+'<a href="https://iris.to/npub16dq3qps8sgehezrylamryx5zrukmhnashvecvjcucjr3927cf2qqd8evcw">☯️iris.to &nbsp;</a>';
web=web+'<a href="https://flycat.club/zh/user/d34110060782337c8864ff76321a821f2dbbcfb0bb33864b1cc48712abd84a80">🐈Flycat</a><a href="https://flycat.club/zh/blog/d34110060782337c8864ff76321a821f2dbbcfb0bb33864b1cc48712abd84a80">博客&nbsp;</a>';
web=web+'<span id="urls">';
web=web+'<a href="https://app.coracle.social/people/npub16dq3qps8sgehezrylamryx5zrukmhnashvecvjcucjr3927cf2qqd8evcw/notes">⚛️Coracle&nbsp;</a>';
web=web+'<a href="https://www.broadcstr.com/npub16dq3qps8sgehezrylamryx5zrukmhnashvecvjcucjr3927cf2qqd8evcw">Broadcstr&nbsp;</a>';
web=web+'<a href="https://yosup.app/profile/d34110060782337c8864ff76321a821f2dbbcfb0bb33864b1cc48712abd84a80">Yosup&nbsp;</a>';
web=web+'<a href="https://web.nostrid.app/account/d34110060782337c8864ff76321a821f2dbbcfb0bb33864b1cc48712abd84a80">Nostrid&nbsp;</a>';
web=web+'<a href="https://snort.social/p/npub16dq3qps8sgehezrylamryx5zrukmhnashvecvjcucjr3927cf2qqd8evcw">Snort&nbsp;</a>';
web=web+'<a href="https://nostr.band/npub16dq3qps8sgehezrylamryx5zrukmhnashvecvjcucjr3927cf2qqd8evcw">Nostr.band&nbsp;</a>';
web=web+'</span>';
document.getElementById("NostrWeb").innerHTML=web;
web='<a href="https://github.com/irislib/iris-messenger/releases" title="Desktop桌面版本的iris">🖥️iris&nbsp;</a>';
web=web+'<a href="https://nostr.info/relays/"><b>Relays </b></a>';
web=web+'<a href="https://nostr.watch/relays/find#public">Map</a>';
web=web+'<a href="https://8nostr.com/relays/?Events=100&ms=3000">&nbsp;8☯️&nbsp;</a>';
web=web+'<a href="https://apps.apple.com/ca/app/damus/id1628663131">🍏Damus&nbsp;</a>';
web=web+'<a href="https://testflight.apple.com/join/kvGz47De">Nostrmo</a>';
web=web+'<a href="https://testflight.apple.com/join/5xdoDCmG" title="Iris">&nbsp;</a>';
web=web+'<a href="https://testflight.apple.com/join/WVoBPXE6">Plebstr</a>';
web=web+'<a href="https://plebstr.com/#download">&nbsp; </a>';
web=web+'<a href="https://github.com/vitorpamplona/amethyst/releases/">📱<b>Amethyst</b></a>&nbsp;';
web=web+'<a href="https://nostrmo.com/releases/1_4_3/app-release.apk">Nostrmo</a>&nbsp;';
web=web+'<a href="https://github.com/KoalaSat/nostros/releases">Nostros</a>&nbsp;';
web=web+'<a href="https://pan.baidu.com/s/1V-TA-o4230Ypt8xqgxjqOw?pwd=doge">[<b>Yun</b>]</a>&nbsp;';
web=web+'<a href="https://yiyan.baidu.com" title="百度文心一言">☮️文心</a>&nbsp;';
web=web+'<a href="https://tongyi.aliyun.com" title="阿里通义千问">通义</a>&nbsp;';
web=web+'<a href="https://nostrurl.com/chat">🤖<b>Chat</b></a>';
web=web+'<a href="https://chatgpt.gengai.net/ChatGPT-QA.html" title="gengai">&nbsp;G</a>';
web=web+'<a href="https://chat1.binjie.site:7777" title="chat1-9">P</a>';
web=web+'<a href="https://chatgpt.ffkey.com/" title="ffkey">T</a>';
web=web+'<a href="https://iris.to/npub1tsgw6pncspg4d5u778hk63s3pls70evs4czfsmx0fzap9xwt203qtkhtk4" title="GPT3">3&nbsp;</a>';
web=web+'<a href="https://susu.email/">合</a>';
web=web+'<a href="https://ai-toolbox.codefuture.top/" title="多种分类多种玩法">用</a>';
document.getElementById("NostrApp").innerHTML=web;
web='<a href="https://lightningaddress.com/">LN@</a>&nbsp;';
web=web+'<a href="https://www.lapps.co/">Lapps</a>&nbsp;';
web=web+'<a href="https://www.bitrefill.com/blog/top-11-lightning-network-wallets-bitrefill/">11</a>&nbsp;';
web=web+'<a href="https://getalby.com/">getAlby</a>';
web=web+'<a href="https://github.com/getAlby/lightning-browser-extension/releases">(Ext)</a>';
web=web+'<a href="https://pan.baidu.com/s/1V-TA-o4230Ypt8xqgxjqOw?pwd=doge"><b>[YUN]</b></a>&nbsp;';
web=web+'<a href="https://github.com/ACINQ/phoenix/releases">Phoenix</a>&nbsp;';
web=web+'<a href="https://github.com/breez/breezmobile/releases">Breez</a>&nbsp;';
web=web+'<a href="https://github.com/muun/apollo">Muun</a>&nbsp;';
web=web+'<a href="https://github.com/ZeusLN/zeus/releases">Zeus</a>&nbsp;';
web=web+'<a href="https://github.com/BlueWallet/BlueWallet/releases">BlueWallet</a>';
web=web+'<a href="https://www.bitrefill.com/thor-lightning-network-channels/?utm_source=medium&utm_medium=blog&utm_campaign=lightning-wallets">&nbsp;BLW</a>';
web=web+'<a href="https://walletofsatoshi.com/">&nbsp;WoS</a>';
document.getElementById("LNlink").innerHTML=web;
web='<a href="https://ahr999.com">9️⃣ahr999.com</a>&nbsp;';
web=web+'<a href="https://btcdv.com">BtcDV.com</a>&nbsp;';
web=web+'<a href="https://btayx.com/btcie.com">📈BtcIE</a>&nbsp;';
web=web+'<a href="https://bitcoinall.org/">BitcoinALL.org</a>&nbsp;';
web=web+'<a href="https://www.bit.pics/">🎨Bit.Pics</a>&nbsp;';
web=web+'<a href="https://idgui.com/n/">idgui.com/n</a>&nbsp;';
web=web+'<a href="https://dogefei.com/">👁️‍🗨️DogeFei</a>&nbsp;';
web=web+'<a href="https://bijingpai.com/">🛒BiJingPai.com</a>&nbsp;';
web=web+'<a href="lightning:cndx@8nostr.com" target=_self>LN</a><a href="https://getalby.com/p/cndx">⚡ &nbsp;</a>';
document.getElementById("Morelink").innerHTML=web;
web='<a target="_self" href="https://ahr999.com" onclick="nip5add(\'ahr999.com\');return false;">@ahr999</a>';
web=web+'<a target="_self" href="https://btcdv.com" onclick="nip5add(\'btcdv.com\');return false;"> @₿dV </a>';
web=web+'<a target="_self" href="https://vbtcv.com" onclick="nip5add(\'vbtcv.com\');return false;">@v₿v</a> ';
web=web+'<a target="_self" href="https://btclv.com" onclick="nip5add(\'btclv.com\');return false;">@₿Lv</a> ';
web=web+'<a target="_self" href="https://btc.pics" onclick="nip5add(\'btc.pics\');return false;">@₿.pics</a> ';
web=web+'<a target="_self" href="https://bitcoinall.org" onclick="nip5add(\'bitcoinall.org\');return false;">@₿all</a>';
document.getElementById("nip5adds").innerHTML=web;
